Warning: truncated output (original token count: 27460)
Total output lines: 4072

# -*- coding: utf-8 -*-
"""Retail_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLJRpTlJrTHuM1aEALE04hKD6J5_KcmL

# Integrated Retail Analytics for Store Optimization and Demand Forecasting

**Author:** Dolly Jain

## Project Objective
Analyze store and department sales, identify unusual patterns,
group similar stores, and forecast weekly sales to support
inventory planning and marketing decisions.

## Datasets
1. Sales — weekly sales by store and department.
2. Features — holidays, markdowns, temperature, and economic indicators.
3. Stores — store types and sizes.

## Connecting Google Drive

We connect Google Drive to the Colab runtime so the notebook
can access the project datasets and save analysis outputs.

The project files are stored in the Retail_Analytics_Project
folder. Files saved to Drive remain available after the
Colab runtime disconnects.
"""

from google.colab import drive

drive.mount('/content/drive')

"""## Locating the Dataset Folder

We define the path to the project's data folder and check
whether it exists.

We list the files inside the folder to confirm that the three
required CSV datasets are available before loading them.
"""

from pathlib import Path

data_folder = Path(
    "/content/drive/MyDrive/Retail_Analytics_Project/data"
)

print("Data folder found:", data_folder.exists())

if data_folder.exists():
    for file in sorted(data_folder.iterdir()):
        print(file.name)

"""## Loading the Datasets

We use Pandas to load the sales, features, and stores CSV files
into three separate DataFrames.

We inspect each DataFrame's shape to confirm its number of
rows and columns. Loading the files does not modify the
original CSV datasets.
"""

import pandas as pd

sales = pd.read_csv(data_folder / "sales data-set.csv")
features = pd.read_csv(data_folder / "Features data set.csv")
stores = pd.read_csv(data_folder / "stores data-set.csv")

print("Sales — rows, columns:", sales.shape)
print("Features — rows, columns:", features.shape)
print("Stores — rows, columns:", stores.shape)

"""### Initial Dataset Dimensions

- Sales: 421,570 rows and 5 columns.
- Features: 8,190 rows and 12 columns.
- Stores: 45 rows and 3 columns.

## Previewing the Sales Dataset

We display the first five rows to understand the sales table's
structure and example values.

Each row represents sales for one store, one department, and
one week.

- Store: store identifier.
- Dept: department identifier.
- Date: the date associated with the sales week.
- Weekly_Sales: weekly sales amount, not product quantity.
- IsHoliday: whether the week is marked as a holiday week.

The displayed row index is not an additional source column.
"""

sales.head()

"""## Previewing the Features Dataset

We inspect the first five rows of the store-week features table.

The dataset contains temperature, fuel price, markdown-related
variables, CPI, unemployment, and a holiday flag. These variables
provide context for investigating sales patterns.

Features are recorded at store-week level, not department level.
They will therefore be joined to sales using Store and Date.

NaN indicates missing information, not necessarily zero.
The exact meanings of the five markdown categories and the
measurement units require confirmation from source documentation.
"""

features.head()

"""## Previewing the Stores Dataset

We inspect the first five rows of the store attributes table.

- Store: store identifier.
- Type: store category, represented by labels such as A, B, and C.
- Size: the recorded store size.

Store attributes will be joined to sales using Store.
The category definitions and size units should be confirmed
from source documentation rather than assumed.
"""

stores.head()

"""## Inspecting Sales Data Types and Completeness

We inspect the sales dataset's column names, data types,
and non-null counts.

This helps identify columns that require conversion and
columns containing missing values. At this stage, Date is
stored as text and will be converted to datetime.

All five sales columns contain 421,570 non-null values.
This confirms completeness of these fields, but does not
establish that every value is valid or every expected week
is present.
"""

sales.info()

print("FEATURES DATA")
features.info()

print("\nSTORES DATA")
stores.info()

"""## Date Conversion

The Date columns in the sales and features datasets are currently
stored as text. We convert them to datetime using the DD/MM/YYYY
format to interpret dates correctly.

This will help us sort records chronologically, analyze sales
trends, and create time-based features such as month and year.
"""

sales["Date"] = pd.to_datetime(
    sales["Date"], format="%d/%m/%Y"
)

features["Date"] = pd.to_datetime(
    features["Date"], format="%d/%m/%Y"
)

print("Sales Date type:", sales["Date"].dtype)
print("Features Date type:", features["Date"].dtype)

print("\nConverted dates:")
print(sales["Date"].head())

"""## Missing Value Analysis

We count missing values in each dataset to identify incomplete
columns and plan an appropriate cleaning strategy.

Missing values are not automatically treated as zero. Their
meaning and distribution will be examined before deciding
how to handle them.
"""

print("Missing values in Sales:")
print(sales.isna().sum())

print("\nMissing values in Features:")
print(features.isna().sum())

print("\nMissing values in Stores:")
print(stores.isna().sum())

"""## Duplicate Record Check

We check for exact duplicate rows in all three datasets.
Repeated records may cause double counting and affect analysis.

This step only identifies duplicates. Any duplicates found
will be investigated before removal.
"""

print("Sales duplicate rows:", sales.duplicated().sum())
print("Features duplicate rows:", features.duplicated().sum())
print("Stores duplicate rows:", stores.duplicated().sum())

"""## Checking Unique Record Keys

Each dataset has a combination of columns that should uniquely
identify a record:

- Sales: Store, Dept, and Date
- Features: Store and Date
- Stores: Store

We check these keys before merging to prevent accidental
duplication of sales records during the join.
"""

print(
    "Repeated Sales keys:",
    sales.duplicated(subset=["Store", "Dept", "Date"]).sum()
)

print(
    "Repeated Features keys:",
    features.duplicated(subset=["Store", "Date"]).sum()
)

print(
    "Repeated Store keys:",
    stores.duplicated(subset=["Store"]).sum()
)

"""## Merging Sales with Features

We join the sales and features datasets using Store and Date.

A left join preserves every sales record and adds the matching
store-week information. We validate the many-to-one relationship
because multiple departments can share one store-week feature record.

A merge indicator helps identify sales records without matching features.
"""

merged_data = sales.merge(
    features,
    on=["Store", "Date"],
    how="left",
    validate="many_to_one",
    suffixes=("", "_features"),
    indicator=True
)

print("Rows before merge:", len(sales))
print("Rows after merge:", len(merged_data))

print("\nMatch status:")
print(merged_data["_merge"].value_counts())

"""## Validating Holiday Flags

Both source datasets contain an IsHoliday column. We compare
these values after merging to check for inconsistencies.
If they match, we keep one copy of the holiday flag.
"""

holiday_mismatches = (
    merged_data["IsHoliday"] != merged_data["IsHoliday_features"]
).sum()

print("Holiday mismatches:", holiday_mismatches)

assert holiday_mismatches == 0, "Holiday flags differ. Investigate before continuing."

merged_data = merged_data.drop(
    columns=["IsHoliday_features", "_merge"]
)

print("Shape after removing repeated columns:", merged_data.shape)

"""## Adding Store Attributes

We merge the store information using Store as the join key.
This adds Type and Size to each sales record.

We preserve all sales rows and verify that every record has
a matching store.
"""

merged_data = merged_data.merge(
    stores,
    on="Store",
    how="left",
    validate="many_to_one",
    indicator=True
)

print("Store match status:")
print(merged_data["_merge"].value_counts())

assert merged_data["_merge"].eq("both").all(), "Some stores did not match."
assert len(merged_data) == len(sales), "The number of sales rows changed."

merged_data = merged_data.drop(columns="_merge")

print("\nFinal merged shape:", merged_data.shape)

"""## Missing Values After Merging

We reassess missing values in the merged dataset because
the features file covers more dates than the sales file.

We calculate both missing counts and percentages to understand
the completeness of the data available for sales analysis.
"""

missing_summary = pd.DataFrame({
    "Missing_Count": merged_data.isna().sum(),
    "Missing_Percent": (
        merged_data.isna().mean() * 100
    ).round(2)
})

display(
    missing_summary[missing_summary["Missing_Count"] > 0]
)

"""## Understanding Data Coverage

We identify the sales period and count the unique stores,
departments, and store-department combinations.

A store-department combination represents one sales time series.
Not every department is necessarily present in every store.
"""

print("First sales date:", merged_data["Date"].min().date())
print("Last sales date:", merged_data["Date"].max().date())

print("Unique stores:", merged_data["Store"].nunique())
print("Unique departments:", merged_data["Dept"].nunique())
print("Unique weeks:", merged_data["Date"].nunique())

series_count = (
    merged_data[["Store", "Dept"]]
    .drop_duplicates()
    .shape[0]
)

print("Store-department combinations:", series_count)

"""## Checking Zero and Negative Sales

We count zero and negative weekly sales before deciding how
to handle them.

Negative sales may represent returns or accounting adjustments,
but this requires confirmation. These records are retained
rather than automatically removed or replaced.
"""

negative_count = (merged_data["Weekly_Sales"] < 0).sum()
zero_count = (merged_data["Weekly_Sales"] == 0).sum()

print("Negative sales records:", negative_count)
print("Zero sales records:", zero_count)

display(
    merged_data.loc[
        merged_data["Weekly_Sales"] < 0,
        ["Store", "Dept", "Date", "Weekly_Sales"]
    ].head()
)

"""## Checking Weekly Continuity

We sort records by store, department, and date, then measure
the gap between consecutive observations within each series.

Gaps longer than seven days indicate missing weekly observations.
An absent observation is not automatically treated as zero sales.
This check identifies internal gaps, not missing periods before
the first or after the last observation of a series.
"""

merged_data = merged_data.sort_values(
    ["Store", "Dept", "Date"]
).reset_index(drop=True)

week_gaps = (
    merged_data.groupby(["Store", "Dept"])["Date"]
    .diff()
    .dt.days
)

print("Most common gaps between observations:")
print(week_gaps.value_counts().head())

print("\nIntervals longer than 7 days:")
print((week_gaps > 7).sum())

"""## Exploratory Data Analysis: Sales Summary

We examine the distribution of weekly sales using descriptive
statistics, including the mean, median, minimum, and maximum.

These statistics help us understand typical sales levels and
the spread of values. Extreme values require investigation
and are not automatically considered errors.
"""

sales_summary = merged_data["Weekly_Sales"].describe()

print(sales_summary.round(2))

"""## Overall Weekly Sales Trend

We aggregate sales across all observed stores and departments
for each week and plot the totals over time.

This helps identify recurring peaks, declines, and possible
seasonal patterns. Changes in data coverage can also affect
aggregated totals.
"""

import matplotlib.pyplot as plt

weekly_sales = (
    merged_data.groupby("Date")["Weekly_Sales"]
    .sum()
    .sort_index()
)

print("Number of observed weeks:", len(weekly_sales))

plt.figure(figsize=(12, 5))

plt.plot(
    weekly_sales.index,
    weekly_sales.values / 1_000_000,
    color="teal"
)

plt.title("Total Weekly Sales Across Stores")
plt.xlabel("Week")
plt.ylabel("Sales Amount (Millions)")
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""## Top Stores by Total Observed Sales

We compare stores using their total sales over the available
historical period.

This identifies the largest sales contributors. Total sales
alone do not measure profitability or efficiency; store size
and observation coverage should also be considered.
"""

store_sales = (
    merged_data.groupby("Store")["Weekly_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Top 10 stores by total sales:")
print(store_sales.head(10).round(2))

top_10 = store_sales.head(10).sort_values()

plt.figure(figsize=(10, 6))

plt.barh(
    top_10.index.astype(str),
    top_10.values / 1_000_000,
    color="steelblue"
)

plt.title("Top 10 Stores by Total Observed Sales")
plt.xlabel("Sales Amount (Millions)")
plt.ylabel("Store ID")
plt.tight_layout()
plt.show()

"""## Holiday and Non-Holiday Sales Comparison

We compare mean and median sales per observed department-week
between holiday and non-holiday weeks.

This is a descriptive comparison. It does not prove that holidays
caused the difference, because seasonality and other factors
may also influence sales.
"""

holiday_summary = (
    merged_data.groupby("IsHoliday")["Weekly_Sales"]
    .agg(["mean", "median", "count"])
    .rename(columns={
        "mean": "Mean_Sales",
        "median": "Median_Sales",
        "count": "Records"
    })
)

display(holiday_summary.round(2))

holiday_summary["Mean_Sales"].plot(
    kind="bar",
    figsize=(7, 4),
    color=["steelblue", "orange"]
)

plt.title("Average Department-Week Sales: Holiday vs Non-Holiday")
plt.xlabel("Holiday Flag")
plt.ylabel("Mean Sales Amount")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""## Monthly Sales Patterns

We compare average department-week sales by calendar month
across the available years.

Using averages avoids directly comparing monthly totals with
different numbers of observed weeks. However, differences in
year and department coverage may still affect the comparison.
"""

monthly_sales = (
    merged_data.assign(
        Month=merged_data["Date"].dt.month
    )
    .groupby("Month")["Weekly_Sales"]
    .mean()
)

display(monthly_sales.round(2))

plt.figure(figsize=(10, 4))

plt.plot(
    monthly_sales.index,
    monthly_sales.values,
    marker="o",
    color="teal"
)

plt.title("Average Department-Week Sales by Month")
plt.xlabel("Month")
plt.ylabel("Mean Sales Amount")
plt.xticks(range(1, 13))
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

"""## Sales Comparison by Store Type

We first calculate total sales for each store-week, then compare
the average store-week sales across store types.

This measures sales at the store level rather than treating each
department as a separate store observation. Differences in store
size and department coverage should be considered when interpreting
the results.
"""

store_week_sales = (
    merged_data.groupby(
        ["Store", "Type", "Date"],
        as_index=False
    )["Weekly_Sales"]
    .sum()
)

type_summary = (
    store_week_sales.groupby("Type")
    .agg(
        Stores=("Store", "nunique"),
        Mean_Store_Weekly_Sales=("Weekly_Sales", "mean"),
        Store_Weeks=("…19460 tokens truncated…ek.to_csv(
    output_folder / "future_thirteen_week_forecast.csv",
    index=False
)

joblib.dump(
    {
        "pipeline": future_core_model,
        "features": forecast_features,
        "training_end": str(last_observed_date.date()),
        "horizon_weeks": 1,
        "versions": forecast_bundle["versions"]
    },
    model_folder / "future_one_week_model.joblib"
)

display(future_thirteen_week.head().round(2))

print("One-week target:", next_week_date.date())
print("13-week target:", target_date_13.date())
print("Future forecasts and refitted model saved.")

"""## Forecast Performance Across Store Segments

We evaluate the selected one-week model separately for each
training-defined store segment using the common test sample.

Segment WAPE is calculated from pooled absolute errors and
absolute actual sales, rather than averaging store percentages.
These diagnostics identify planning risks without changing
the frozen model.
"""

segment_test = test_scored.merge(
    store_profiles[["Store", "Segment", "Segment_Name"]],
    on="Store",
    how="left",
    validate="many_to_one"
)

assert segment_test["Segment"].notna().all()

segment_error_rows = []

for segment, group in segment_test.groupby("Segment"):
    actual = group["Weekly_Sales"]
    error = group["Core_Prediction"] - actual
    denominator = actual.abs().sum()

    segment_error_rows.append({
        "Segment": segment,
        "Segment_Name": group["Segment_Name"].iloc[0],
        "Stores": group["Store"].nunique(),
        "Scored_Records": len(group),
        "MAE": error.abs().mean(),
        "WAPE_Percent": (
            error.abs().sum() / denominator * 100
            if denominator > 0 else np.nan
        ),
        "Bias_Percent": (
            error.sum() / denominator * 100
            if denominator > 0 else np.nan
        )
    })

segment_errors = pd.DataFrame(segment_error_rows)

display(segment_errors.round(2))

segment_errors.to_csv(
    output_folder / "segment_forecast_errors.csv",
    index=False
)

"""## Segment-Level Future Sales Planning

We summarize future sales forecasts by segment, target date,
and forecast horizon.

The one-week and thirteen-week forecasts refer to different
target weeks and use different approaches. Their totals are
kept separate and should not be treated as cumulative demand
or directly interpreted as a growth forecast.
"""

forecast_summary_columns = [
    "Store", "Dept", "Target_Date",
    "Horizon_Weeks", "Prediction"
]

future_combined = pd.concat(
    [
        future_one_week[forecast_summary_columns],
        future_thirteen_week[forecast_summary_columns]
    ],
    ignore_index=True
)

future_combined = future_combined.merge(
    store_profiles[["Store", "Segment", "Segment_Name"]],
    on="Store",
    how="left",
    validate="many_to_one"
)

assert future_combined["Segment"].notna().all()

segment_future_forecasts = (
    future_combined.groupby(
        ["Segment_Name", "Target_Date", "Horizon_Weeks"],
        as_index=False
    )
    .agg(
        Stores=("Store", "nunique"),
        Department_Records=("Dept", "size"),
        Predicted_Sales=("Prediction", "sum")
    )
)

display(segment_future_forecasts.round(2))

segment_future_forecasts.to_csv(
    output_folder / "segment_future_forecasts.csv",
    index=False
)

"""## Inventory and Marketing Recommendations

We propose differentiated planning actions based on observed
segment characteristics.

Higher-variability stores require closer forecast review.
More stable stores can use regular planning cycles with exception
monitoring. Holiday patterns motivate controlled promotional
pilots, not claims of proven promotion effectiveness.

Sales forecasts are monetary amounts. Reorder quantities and
safety stock require unit demand, inventory, lead times, and
service-level targets, which are unavailable.
"""

higher_variability_segment = (
    segment_summary["Mean_Sales_CV"].idxmax()
)

strategy_rows = []

for segment, profile in segment_summary.iterrows():
    higher_variability = (
        segment == higher_variability_segment
    )

    strategy_rows.append({
        "Segment": segment,
        "Segment_Name": segment_names[segment],
        "Mean_Sales_CV": profile["Mean_Sales_CV"],
        "Mean_Holiday_Ratio": profile["Mean_Holiday_Ratio"],
        "Inventory_Planning": (
            "Review forecasts and large sales changes weekly; "
            "check stock and lead times before adjusting orders."
            if higher_variability else
            "Use a regular replenishment review cycle with "
            "alerts for deviations from the usual sales pattern."
        ),
        "Marketing_Pilot": (
            "Test holiday-timed campaigns against comparable "
            "holdout stores; evaluate incremental margin."
            if higher_variability else
            "Test smaller targeted campaigns with holdout stores; "
            "check whether benefits justify promotion costs."
        ),
        "Required_Additional_Data": (
            "Unit sales, stock levels, lead times, margins, "
            "promotion costs and transaction records."
        )
    })

strategy_table = pd.DataFrame(strategy_rows)

display(strategy_table)

strategy_table.to_csv(
    output_folder / "segment_business_strategies.csv",
    index=False
)

print("Segment strategy table saved.")

"""## Checking Clustering Initialization Stability

We repeat K-Means with different random seeds while keeping
the same features and number of clusters.

Adjusted Rand Index (ARI) compares each result with the selected
clustering, accounting for arbitrary cluster label numbering.
An ARI of 1 indicates identical group assignments.

This checks sensitivity to initialization only. It does not
establish stability across different samples or future periods.
"""

from sklearn.metrics import adjusted_rand_score

stability_results = []

reference_labels = best_cluster_model.labels_

for seed in [0, 10, 21, 42, 100]:
    repeat_model = KMeans(
        n_clusters=best_k,
        n_init=20,
        random_state=seed
    )

    repeat_labels = repeat_model.fit_predict(
        scaled_store_features
    )

    stability_results.append({
        "Random_Seed": seed,
        "ARI_vs_Selected_Model": adjusted_rand_score(
            reference_labels,
            repeat_labels
        )
    })

cluster_stability = pd.DataFrame(stability_results)

display(cluster_stability.round(3))

cluster_stability.to_csv(
    output_folder / "cluster_initialization_stability.csv",
    index=False
)

"""## Final Consistency Checks

We verify that merging preserved sales rows and totals, forecast
splits respect time boundaries, and future predictions have
unique keys and finite values.

These checks detect implementation issues. They do not prove
that forecasts will be accurate or that all data-quality issues
have been resolved.
"""

# Merging must preserve observed sales.
assert len(merged_data) == len(sales)

assert np.isclose(
    merged_data["Weekly_Sales"].sum(),
    sales["Weekly_Sales"].sum()
)

assert not merged_data.duplicated(
    ["Store", "Dept", "Date"]
).any()

# One-week evaluation cutoff.
assert (
    final_training_data["Date"].max()
    <= test_model_data["Date"].min() - pd.Timedelta(weeks=1)
)

# Thirteen-week training and selection cutoffs.
assert (
    train_13["Target_Date"].max()
    <= validation_13["Origin_Date"].min()
)

assert (
    validation_13["Target_Date"].max()
    <= test_13["Origin_Date"].min()
)

# Future forecast checks.
for forecast_frame, horizon in [
    (future_one_week, 1),
    (future_thirteen_week, 13)
]:
    assert not forecast_frame.duplicated(
        ["Store", "Dept", "Target_Date"]
    ).any()

    assert np.isfinite(
        forecast_frame["Prediction"].to_numpy()
    ).all()

    assert (
        forecast_frame["Target_Date"]
        - forecast_frame["Origin_Date"]
    ).eq(pd.Timedelta(weeks=horizon)).all()

    assert (
        forecast_frame["Target_Date"] > last_observed_date
    ).all()

print("Sales row count and totals preserved.")
print("Record keys are unique.")
print("Forecast time boundaries passed.")
print("Future forecast keys, values, and horizons passed.")

"""## Project Results Summary

We consolidate the selected approaches, test performance,
segmentation results, and analytical limitations.

The summary distinguishes sales-amount forecasts from unit demand
and department associations from actual customer baskets.
It forms a starting point for the detailed project documentation.
"""

report_folder = data_folder.parent / "reports"
report_folder.mkdir(parents=True, exist_ok=True)

one_week_metrics = test_metrics.loc[
    test_metrics["Model"] == "Selected core model"
].iloc[0]

thirteen_week_metrics = test_metrics_13.loc[
    test_metrics_13["Model"] == "Selected seasonal baseline"
].iloc[0]

selected_cluster_quality = cluster_quality.loc[
    cluster_quality["Clusters"] == best_k
].iloc[0]

summary_text = f"""# Integrated Retail Analytics: Results Summary

## Data
- Sales observations: {len(sales):,}
- Stores: {sales["Store"].nunique()}
- Department IDs: {sales["Dept"].nunique()}
- Sales period: {sales["Date"].min().date()} to {last_observed_date.date()}
- Raw source files were preserved.

## One-Week Forecasting
Selected approach: Core gradient boosting.
- Test MAE: {one_week_metrics["MAE"]:.2f}
- Test RMSE: {one_week_metrics["RMSE"]:.2f}
- Test WAPE: {one_week_metrics["WAPE_Percent"]:.2f}%
- Common comparison observations: {len(test_scored):,}

Adding lagged external features did not improve validation MAE
under the tested settings.

## Thirteen-Week Forecasting
Selected approach: Seasonal baseline, chosen by validation MAE.
- Test MAE: {thirteen_week_metrics["MAE"]:.2f}
- Test RMSE: {thirteen_week_metrics["RMSE"]:.2f}
- Test WAPE: {thirteen_week_metrics["WAPE_Percent"]:.2f}%
- Evaluated observations: {len(test_results_13):,}

Both evaluations use rolling forecast origins. Different horizons
may cover different store-department observations.

## Store Segmentation
- Selected clusters: {best_k}
- Silhouette: {selected_cluster_quality["Silhouette"]:.3f}
- Davies-Bouldin: {selected_cluster_quality["Davies_Bouldin"]:.3f}

Segments describe stores, not individual customers.
Initialization stability results are saved separately.

## Anomalies and Department Associations
Unusual observations were flagged for review rather than
automatically deleted. Verified anomaly labels are unavailable.

Department rules describe co-occurring strong-sales events.
They do not establish joint purchases or causal relationships.

## Future Forecasts
- One-week target: {next_week_date.date()}
- Thirteen-week target: {target_date_13.date()}
- Forecasts cover pairs observed in the latest sales week.
- Predictions are sales amounts, not product quantities.

## Business Application
Use segment-specific planning reviews and controlled marketing
pilots. Reorder quantities require unit demand, stock levels,
lead times, and service targets.

## Limitations
Missing markdowns remain unknown. External-factor comparisons
are predictive, not causal. Prediction intervals and broader
historical backtesting are not included in this version.

## Submission Work Remaining
Adapt to the official template if supplied, write detailed
Google Docs documentation, publish the GitHub repository,
verify sharing permissions, and record the presentation.
"""

summary_path = report_folder / "project_results_summary.md"

summary_path.write_text(summary_text, encoding="utf-8")

print(summary_text)
print("\nSaved:", summary_path)

"""## Exporting Supporting Analysis Tables

We save the data-quality summary, missing-value summary, and
anomaly review examples for documentation.

The anomaly export is a review shortlist, not a list of confirmed
errors. Original sales values remain unchanged.
"""

data_quality_summary = pd.DataFrame([
    {
        "Dataset": name,
        "Rows": len(dataset),
        "Columns": dataset.shape[1],
        "Exact_Duplicates": int(dataset.duplicated().sum()),
        "Missing_Cells": int(dataset.isna().sum().sum())
    }
    for name, dataset in [
        ("Sales", sales),
        ("Features", features),
        ("Stores", stores)
    ]
])

data_quality_summary.to_csv(
    output_folder / "data_quality_summary.csv",
    index=False
)

missing_summary.rename_axis("Column").reset_index().to_csv(
    output_folder / "merged_missing_values.csv",
    index=False
)

anomaly_review = anomaly_data[
    anomaly_data["Anomaly_Status"] == "Review"
].nlargest(100, "Anomaly_Score")

anomaly_review[
    [
        "Store", "Dept", "Date", "Weekly_Sales",
        "Sales_Change", "IsHoliday", "Anomaly_Score"
    ]
].to_csv(
    output_folder / "anomaly_review_top_100.csv",
    index=False
)

display(data_quality_summary)

print("Supporting analysis tables saved.")

"""## Saving Exploratory Charts for Reporting

We save the overall weekly sales trend and the holiday comparison
as image files for inclusion in the project documentation.

The holiday chart compares mean department-week sales. It does
not measure the causal effect of holidays.
"""

# Chart 1: Overall weekly sales.
fig, ax = plt.subplots(figsize=(12, 5))

ax.plot(
    weekly_sales.index,
    weekly_sales.values / 1_000_000,
    color="teal"
)

ax.set_title("Total Weekly Sales Across Stores")
ax.set_xlabel("Week")
ax.set_ylabel("Sales Amount (Millions)")
ax.grid(alpha=0.3)

fig.tight_layout()
fig.savefig(
    output_folder / "overall_weekly_sales.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()
plt.close(fig)

# Chart 2: Mean sales in holiday and non-holiday weeks.
fig, ax = plt.subplots(figsize=(7, 4))

holiday_summary["Mean_Sales"].plot(
    kind="bar",
    ax=ax,
    color=["steelblue", "orange"]
)

ax.set_title("Average Department-Week Sales by Holiday Flag")
ax.set_xlabel("Holiday Flag")
ax.set_ylabel("Mean Sales Amount")
ax.tick_params(axis="x", rotation=0)

fig.tight_layout()
fig.savefig(
    output_folder / "holiday_sales_comparison.png",
    dpi=150,
    bbox_inches="tight"
)

plt.show()
plt.close(fig)

print("Both report charts saved.")

"""## Creating a Project Backup

We archive the project files currently available in Google Drive,
excluding existing ZIP archives.

The backup preserves the current work. It is not the final
submission: documentation links, repository publishing, and
the individual presentation still need to be completed.
"""

from zipfile import ZipFile, ZIP_DEFLATED

project_folder = data_folder.parent
backup_path = project_folder / "retail_project_backup.zip"

files_to_archive = [
    path
    for path in project_folder.rglob("*")
    if path.is_file() and path.suffix.lower() != ".zip"
]

notebook_files = [
    path for path in files_to_archive
    if path.suffix.lower() == ".ipynb"
]

with ZipFile(backup_path, "w", ZIP_DEFLATED) as archive:
    for path in files_to_archive:
        archive.write(
            path,
            arcname=str(path.relative_to(project_folder.parent))
        )

print("Files included:", len(files_to_archive))
print("Notebook files included:", len(notebook_files))
print(
    "Backup size (MB):",
    round(backup_path.stat().st_size / 1_000_000, 2)
)
print("Backup saved at:", backup_path)

if not notebook_files:
    print(
        "Notebook not found in this folder. Download it from "
        "Colab as .ipynb, upload it to the project folder, "
        "and rerun this backup cell."
    )
